[package]
name = "ratatoskr-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ratatoskr-core.workspace = true
rig-core.workspace = true
rig-agent.workspace = true
rmcp.workspace = true
thiserror.workspace = true

[lints]
workspace = true
